import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Open_Sans } from "next/font/google"
import "./globals.css";

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-open-sans",
})

export const metadata: Metadata = {
  title: "Grangou - Creator CRM",
  description: "Generated by Grangou app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.className} antialiased`}
      >
        {children}
        <Toaster richColors closeButton theme="light"/>
      </body>
    </html>
  );
}
